### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PoiDoex8** [Iuke121/NaoParse#3]
When more then one Morrighan window is active the program crashes currently

**Comment by LukasTD** [comment]
That's right, does morrighan only support one session? As in you have to launch a new morrighan window per client? If you are multiclienting, I recommend launching extra clients without morrighan, keeping morrighan only for the one you wish to parse. Parsing packets directed to multiple clients can be a little weird. Not impossible though, let me know what behavior you would prefer regarding this.

**Comment by PoiDoex8** [comment]
you can have a different morrighan running for each client. 
preferred behavior would be a packet provider selector eg the same style that pale uses.

**Comment by LukasTD** [comment]
Fixed in https://github.com/Iuke121/NaoParse/commit/fea6f0d8b3f0ea532f2a83361c75f77113855eaf , added an Alissa Selector
